version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: diploma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: moliksey
      POSTGRES_PASSWORD: diploma
      POSTGRES_DB: diploma_db
    ports:
      - "5432:5432"
    volumes:
      - D:/postgres_data:/var/lib/postgresql/data  # Изменили том на bind mount
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moliksey -d diploma_db"]
      interval: 10s
      timeout: 5s
      retries: 5
